module SWT
  Base = Java.type("org.eclipse.swt.SWT")
  Display = Java.type("org.eclipse.swt.widgets.Display")
  Shell = Java.type("org.eclipse.swt.widgets.Shell")
  Button = Java.type("org.eclipse.swt.widgets.Button")
  DropTarget = Java.type("org.eclipse.swt.dnd.DropTarget")
  FileTransfer = Java.type("org.eclipse.swt.dnd.FileTransfer")
  DND = Java.type("org.eclipse.swt.dnd.DND")
  Image = Java.type("org.eclipse.swt.graphics.Image")
  Canvas = Java.type("org.eclipse.swt.widgets.Canvas")
  Color = Java.type("org.eclipse.swt.graphics.Color")
  Spinner = Java.type("org.eclipse.swt.widgets.Spinner")
  Composite = Java.type("org.eclipse.swt.widgets.Composite")
  GridLayout = Java.type("org.eclipse.swt.layout.GridLayout")
  GridData = Java.type("org.eclipse.swt.layout.GridData")
  Label = Java.type("org.eclipse.swt.widgets.Label")
  Text = Java.type("org.eclipse.swt.widgets.Text")
  CocoaOS = Java.type("org.eclipse.swt.internal.cocoa.OS")
  ColorDialog = Java.type("org.eclipse.swt.widgets.ColorDialog")
  Scale = Java.type("org.eclipse.swt.widgets.Scale")
  Combo = Java.type("org.eclipse.swt.widgets.Combo")
  Font = Java.type("org.eclipse.swt.graphics.Font")
  ProgressBar = Java.type("org.eclipse.swt.widgets.ProgressBar")
  MessageBox = Java.type("org.eclipse.swt.widgets.MessageBox")
end
